#!/bin/bash

NODE_COUNT=$1
GROUP_SIZE=$2
BASE_DIR="./bench-ltp-group"
BIN_NAME="mls_in_line_v11"

if [ -z "$NODE_COUNT" ] || [ -z "$GROUP_SIZE" ]; then
    echo "Usage: ./run_mls_clients.sh <number_of_nodes> <initial_group_size>"
    exit 1
fi

if ! command -v tmux &> /dev/null; then
    echo "Error: tmux not found. This script requires tmux."
    exit 1
fi

# Absolute path to top-level ION_NODE_LIST_DIR
# ROOT_DIR="/home/ubuntu/Desktop/ion/ION-DTN/demos/"
ROOT_DIR="$(pwd)"
# ROOT_DIR="/Users/xisentian/Research/dtnwork/ion-dtn-mls/"

# Create a new tmux session
SESSION_NAME="mls_clients"
tmux new-session -d -s "$SESSION_NAME"

i=0
for NODE in $(seq 1 "$NODE_COUNT"); do
    NODE_DIR="${BASE_DIR}/${NODE}.bench.ltp"
    ABS_NODE_DIR=$(realpath "$NODE_DIR")
    SOURCE_EID="ipn:${NODE}.1"

    if [ "$NODE" -eq 1 ]; then
        CMD="./$BIN_NAME $GROUP_SIZE $SOURCE_EID"
    else
        DEST_EID="ipn:1.1"
        CMD="./$BIN_NAME $GROUP_SIZE $SOURCE_EID $DEST_EID"
    fi

    echo "[INFO] Starting $CMD in $NODE_DIR"
    
    sleep 1

    if [ "$NODE" -eq 1 ]; then
        # First node in the main tmux window
        tmux send-keys -t "$SESSION_NAME" "cd '$ABS_NODE_DIR'; export ION_NODE_LIST_DIR='$ROOT_DIR'; $CMD |& tee -a 'mls_output_node${NODE}.log'" Enter
    elif [ "$NODE" -eq 2 ]; then
        # Second node in a new tmux pane
        tmux split-window -h -t "$SESSION_NAME"
        tmux send-keys -t "$SESSION_NAME" "cd '$ABS_NODE_DIR'; export ION_NODE_LIST_DIR='$ROOT_DIR'; $CMD |& tee -a 'mls_output_node${NODE}.log'" Enter
    else
        # Subsequent nodes run in the background
        (
            cd "$ABS_NODE_DIR"
            export ION_NODE_LIST_DIR="$ROOT_DIR"
            $CMD > "mls_output_node${NODE}.log" 2>&1 &
        )
    fi

    i=$((i + 1))
# Files generated by creating ion-nodes)
done

# Attach to the tmux session
tmux attach-session -t "$SESSION_NAME"